### ISSUE TITLE
The efficiency of qoi format in delphi

### ISSUE THREAD

**Issue by dbyoung720** [DosWorld/pasqoi#1]
Have you tested the efficiency of qoi format in delphi?
It encodes and decodes ten times slower than libpng in Delphi.
test source: [TestQOI](https://github.com/dbyoung720/TestQOI)

Your code cannot be compiled in Delphi 11.
Which version are you using?

**Comment by DosWorld** [comment]
Hello!

I am use a "Turbo Pascal  Version 7.0  Copyright (c) 1983,92 Borland International".

**pasqoi** - was written for MS-DOS compiler and with x86 (16-bit real mode) architecture restrictions. Restriction is

_you cant handle memory structure bigger then 65535 bytes (64kb)_

So, i must work via buffered i/o and **each** time check is enough space in buffer (IMHO, this a reason why it slow). Addition improvement - implement it into Borland builtin assembler;

So, i'll add implementation for 32/64-bit world ("memory- > memory" without buffering) in clean Pascal (without asm), in a next few days. This implementation wil support DPMI and Delphi (32/64).

**Comment by dbyoung720** [comment]
OK, Thanks!
